### ISSUE TITLE
Spark standalone not working

### ISSUE THREAD

**Issue by allixender** [geotrellis/geotrellis#1099]
**GSoc2015 GeoTrellis Cassandra tracker for shared scratch documentation**

It seems, [geotrellis-spark cassandra geotiff ingest](https://github.com/kyeah/gt-admin/blob/master/ingest-cassandra.sh) doesn't work with a spark standalone build, presumably geotrellis-spark geotiff ingest in general (e.g. accumulo/hdfs jobs). Gonna try with with a Hadoop 2.6 distro and spark pre-built with hadoop.

For Cassandra's no dependencies just Java deployment possibilities would be nice possibly to not have that geotrellis-spark hadoop dependency?

**For general info - the original issue is resolved** (this thread is kept for accumulating more documentation)

Solution was, either provide external hadoop libraries to your Spark environment, or use a Spark distro that has hadoop bindings included/is built against a hadoop version.

geotrellis-spark assembly jar **does not** contain those hadoop libraries used e.g. by HdfsUtils.scala...

**Comment by pomadchin** [comment]
Seems to me this error not depends on a hadoop / accumulo / spark versions, try to compile and run some ingest jobs on any version before this commit: https://github.com/geotrellis/geotrellis/commit/8266b96d9b59cb9106a6fd5146040afd3962bfea

**Comment by lossyrob** [comment]
Can you give the specific error you're running into?

**Comment by allixender** [comment]
Ok, so the original error that I got was with **sparl-1.2.0** source distro which I build stand-alone. Started the local spark master with `sbin/start-master.sh`

```bash
[akmoch@acer1 geotrellis-cassandra]$ ./casingest.sh 
        zip warning: name not matched: META-INF/ECLIPSEF.RSA

zip error: Nothing to do! (/home/akmoch/dev/build/geotrellis-cassandra/spark/target/scala-2.10/geotrellis-spark-assembly-0.10.0-SNAPSHOT.jar)
        zip warning: name not matched: META-INF/ECLIPSEF.SF

zip error: Nothing to do! (/home/akmoch/dev/build/geotrellis-cassandra/spark/target/scala-2.10/geotrellis-spark-assembly-0.10.0-SNAPSHOT.jar)
16:04:58 Slf4jLogger: Slf4jLogger started
16:04:58 Remoting: Starting remoting
16:04:59 Remoting: Remoting started; listening on addresses :[akka.tcp://sparkDriver@161-65-43-142-ip.gns.cri.nz:47942]
16:05:01 Cluster: New Cassandra host /127.0.0.1:9042 added
16:05:01 CassandraConnector: Connected to Cassandra cluster: Test Cluster
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.hadoop.mapreduce.Job.getInstance(Lorg/apache/hadoop/conf/Configuration;)Lorg/apache/hadoop/mapreduce/Job;
        at geotrellis.spark.io.hadoop.HdfsUtils$.putFilesInConf(HdfsUtils.scala:57)
        at geotrellis.spark.io.hadoop.package$HadoopConfigurationWrapper.withInputDirectory(package.scala:55)
        at geotrellis.spark.io.hadoop.HadoopSparkContextMethods$class.hadoopGeoTiffRDD(HadoopSparkContextMethods.scala:29)
        at geotrellis.spark.io.hadoop.package$HadoopSparkContextMethodsWrapper.hadoopGeoTiffRDD(package.scala:43)
        at geotrellis.spark.ingest.CassandraIngestCommand$$anonfun$main$1.apply(CassandraIngestCommand.scala:41)
        at geotrellis.spark.ingest.CassandraIngestCommand$$anonfun$main$1.apply(CassandraIngestCommand.scala:40)
        at geotrellis.spark.io.cassandra.Cassandra$.withSession(Cassandra.scala:19)
        at geotrellis.spark.ingest.CassandraIngestCommand$.main(CassandraIngestCommand.scala:40)
        at geotrellis.spark.ingest.CassandraIngestCommand$.main(CassandraIngestCommand.scala:29)
        at com.quantifind.sumac.ArgMain$class.mainHelper(ArgApp.scala:45)
        at com.quantifind.sumac.ArgMain$class.main(ArgApp.scala:34)
        at geotrellis.spark.ingest.CassandraIngestCommand$.main(CassandraIngestCommand.scala:29)
        at geotrellis.spark.ingest.CassandraIngestCommand.main(CassandraIngestCommand.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.deploy.SparkSubmit$.launch(SparkSubmit.scala:358)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:75)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
16:05:01 CassandraConnector: Disconnected from Cassandra cluster: Test Cluster
```

@pomadchin I am not really sure how to test a cassandra ingest from the feature-cassandra branch based on a prior geotrellis-master revision? Interestingly, the pull request you mentioned is actually after the last edits in the feature/cassandra branch.

However, the CassandraIngestCommand relies on hadoop functionality in the geotrellis-spark module:

`geotrellis.spark.io.hadoop.HdfsUtils$.putFilesInConf(HdfsUtils.scala:57)`

Not sure, why the CassandraIngest needs HdfsUtils? Because the GeoTIFF might residing in a HDFS to be ingested in a Cassandra?

Not sure, if the hadoop-2.5.0 jars are included in the geotrellis-spark assembly or if they'll be provided through the Spark/Hadoop execution environment?

So I tried the **spark-1.2.2-bin-hadoop2.4 distro** from Apache Spark downloads and started the local master `sbin/start-master.sh`.

I have a vanilla **hadoop-2.6.0.tar.gz** from Apache Hadoop downloads, but I don't have it running. I am not sure yet, how the setup is, having which hadoop service running or not and how to tell the spark installation where and how to use the hadoop environment?

However, when running the cassandra ingest, it still fails with an error:

```bash
[akmoch@acer1 geotrellis-cassandra]$ ./casingest.sh                    
        zip warning: name not matched: META-INF/ECLIPSEF.RSA

zip error: Nothing to do! (/home/akmoch/dev/build/geotrellis-cassandra/spark/target/scala-2.10/geotrellis-spark-assembly-0.10.0-SNAPSHOT.jar)
        zip warning: name not matched: META-INF/ECLIPSEF.SF

zip error: Nothing to do! (/home/akmoch/dev/build/geotrellis-cassandra/spark/target/scala-2.10/geotrellis-spark-assembly-0.10.0-SNAPSHOT.jar)
Spark assembly has been built with Hive, including Datanucleus jars on classpath
17:40:21 Slf4jLogger: Slf4jLogger started
17:40:21 Remoting: Starting remoting
17:40:22 Remoting: Remoting started; listening on addresses :[akka.tcp://sparkDriver@161-65-43-142-ip.gns.cri.nz:51617]
17:40:22 NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
17:40:24 Cluster: New Cassandra host /127.0.0.1:9042 added
17:40:24 CassandraConnector: Connected to Cassandra cluster: Test Cluster
Exception in thread "main" java.lang.IllegalArgumentException: Can not create a Path from an empty string
        at org.apache.hadoop.fs.Path.checkPathArg(Path.java:127)
        at org.apache.hadoop.fs.Path.<init>(Path.java:135)
        at org.apache.hadoop.util.StringUtils.stringToPath(StringUtils.java:241)
        at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.setInputPaths(FileInputFormat.java:454)
        at geotrellis.spark.io.hadoop.HdfsUtils$.putFilesInConf(HdfsUtils.scala:58)
        at geotrellis.spark.io.hadoop.package$HadoopConfigurationWrapper.withInputDirectory(package.scala:55)
        at geotrellis.spark.io.hadoop.HadoopSparkContextMethods$class.hadoopGeoTiffRDD(HadoopSparkContextMethods.scala:29)
        at geotrellis.spark.io.hadoop.package$HadoopSparkContextMethodsWrapper.hadoopGeoTiffRDD(package.scala:43)
        at geotrellis.spark.ingest.CassandraIngestCommand$$anonfun$main$1.apply(CassandraIngestCommand.scala:41)
        at geotrellis.spark.ingest.CassandraIngestCommand$$anonfun$main$1.apply(CassandraIngestCommand.scala:40)
        at geotrellis.spark.io.cassandra.Cassandra$.withSession(Cassandra.scala:19)
        at geotrellis.spark.ingest.CassandraIngestCommand$.main(CassandraIngestCommand.scala:40)
        at geotrellis.spark.ingest.CassandraIngestCommand$.main(CassandraIngestCommand.scala:29)
        at com.quantifind.sumac.ArgMain$class.mainHelper(ArgApp.scala:45)
        at com.quantifind.sumac.ArgMain$class.main(ArgApp.scala:34)
        at geotrellis.spark.ingest.CassandraIngestCommand$.main(CassandraIngestCommand.scala:29)
        at geotrellis.spark.ingest.CassandraIngestCommand.main(CassandraIngestCommand.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.deploy.SparkSubmit$.launch(SparkSubmit.scala:358)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:75)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
17:40:25 CassandraConnector: Disconnected from Cassandra cluster: Test Cluster
```

So obviously it now takes the hadoop libraries from the spark 1.2.2-hadoop distro. But it fails on a empty path parameter.

Ok, found that comment in HdfsUtils.scala(line):

```scala
  /* 
   * Recursively descend into a directory and and get list of file paths
   * The input path can have glob patterns
   *    e.g. /geotrellis/images/ne*.tif
   * to only return those files that match "ne*.tif" 
   */ 
  def listFiles(path: Path, conf: Configuration): List[Path] = {
...
```

Copied test rasters to comply to that rule and now the CassandraIngestCommand would read them.

Apart of that I am now struggling with connection to the cassandra database as the --host parameter doesn't seem to be honoured, this issue is still a good documentation of the reason, why Spark Standalone wouldn't work. Because Hadoop dependency is hard-coded through the use of HdfsUtils (to read recursively through directory).

**Comment by lossyrob** [comment]
That error is coming from HDFS reading the source rasters via the local file system. For Spark to interact with the local file system we use HDFS. Can you post your ingest shell script? What is the input parameter? Are you sure that directly exists? Did you prefix it correctly with `file://`?

**Comment by allixender** [comment]
Well, as I stated before, the ingest now works and I can start learning how the indexing and filtering is happening as of now in the geotrellis-spark-cassandra branch.

The ingest script is this one:

```bash
### INGEST SPATIAL GEOTIFF IN CASSANDRA ###
# geotrellis-spark JAR. Shouldn't have to change this one if running in the root folder (remember to run ./sbt "project spark" assembly)
JAR=/home/akmoch/dev/build/geotrellis-cassandra/spark/target/scala-2.10/geotrellis-spark-assembly-0.10.0-SNAPSHOT.jar

# Directory with the input tiled GeoTIFF's, need to comply to ../ne*.tif rule **weird?*
# INPUT=file:/home/akmoch/dev/build/geotrellis-cassandra/raster-test/data/one-month-tiles-tiff
INPUT=/home/akmoch/dev/build/geotrellis-cassandra/raster-test/data/one-month-tiles-tiff

export SPARK_HOME=/home/akmoch/dev/spark-1.2.2-bin-hadoop2.4

# Table to store tiles
TABLE=nexmonth

# Name of the layer. This will be used in conjunction with the zoom level to reference the layer (see LayerId)
LAYER_NAME=nexmonth

# This defines the destination spatial reference system we want to use
# (in this case, Web Mercator)
CRS=EPSG:3857

# true means we want to pyramid the raster up to larger zoom levels,
# so if our input rasters are at a resolution that maps to zoom level 11, pyramiding will also save
# off levels 10, 9, ..., 1.
PYRAMID=true

# true will delete the HDFS data for the layer if it already exists.
# CLOBBER=true
CLOBBER=false
# true will delete the HDFS data for the layer if it already exists.
# CLOBBER=true
CLOBBER=false

# We need to remove some bad signatures from the assembled JAR. We're working on excluding these
# files as part of the build step, this is a workaround.
zip -d $JAR META-INF/ECLIPSEF.RSA
zip -d $JAR META-INF/ECLIPSEF.SF

# Run the spark submit job

# sbt, sbt assembly to gen JAR

$SPARK_HOME/bin/spark-submit \
--class geotrellis.spark.ingest.CassandraIngestCommand \
$JAR \
--host localhost --keyspace ingest \
--crs $CRS \
--pyramid $PYRAMID --clobber $CLOBBER \
--input $INPUT \
--layerName $LAYER_NAME \
--table $TABLE
```

In fact I did try with `file:/` and without. But it didn't work before I realised this filtering on **ne*.tif* would be applied.

**Comment by allixender** [comment]
Notes: 

- gotta read https://github.com/geotrellis/geotrellis/issues/3 
- KeyIndex Range check and io.cassandra.spatial.SpatialRasterRDDReader check!!! => it's right in space time
- check with Accumulo RastercatalogSpec.scala test every single tile
- tif vs/and .tiff extension, input glob pattern should match the files
- recursive is wanted? (I think we want yes, but in fact right now it doesn't really? To be verified, in Cassandra branch or also master? )

**Comment by lossyrob** [comment]
Hey @allixender, I feel like this issue has gotten away a bit from it's title...can you rename it or close?

**Comment by allixender** [comment]
ok, closing. For general info still: Spark standalone is not working, because it depends on external (or bundled in Spark distro) Hadoop libraries.
