### ISSUE TITLE
geotrellis-master builds failed on my machine

### ISSUE THREAD

**Issue by zsyet** [geotrellis/geotrellis#1130]
i inserted proxy setting, like -Dhttp.proxyHost=xxx -Dhttp.proxyPort=xxx -Dhttp.proxyUser=xxx -Dhttp.proxyPassword=xxx -Dhttps.proxyHost=xxx -Dhttps.proxyPort=xxx -Dhttps.proxyUser=xxx -Dhttps.proxyPassword=xxx, into buildall.sh, and ran ./buildall.sh
sbt-launcher.jar is downloaded and sbt started, it seemed the proxy setting was right, but sbt aborted soon with exception:
typesafe-ivy-releases: no namespace defined: using system
	no ivy file in cache for org.scala-sbt#sbt;0.13.8: tried /root/.ivy2/cache/org.scala-sbt/sbt/ivy-0.13.8.xml
	 trying https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.8/ivys/ivy.xml
		tried https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.8/ivys/ivy.xml
authenicating to proxy server with username [z00247304]
problem occurred while resolving dependency: org.scala-sbt#sbt;0.13.8 {default=[default(compile)]} with typesafe-ivy-releases: java.lang.RuntimeException: java.util.NoSuchElementException
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1241)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:2713)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:477)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.apache.ivy.util.url.BasicURLHandler.checkStatusCode(BasicURLHandler.java:130)
	at org.apache.ivy.util.url.BasicURLHandler.getURLInfo$57a0216e(BasicURLHandler.java:73)
	at org.apache.ivy.util.url.BasicURLHandler.getURLInfo(BasicURLHandler.java:54)
	at org.apache.ivy.plugins.repository.url.URLResource.init(URLResource.java:65)
	at org.apache.ivy.plugins.repository.url.URLResource.exists(URLResource.java:81)
	at org.apache.ivy.plugins.resolver.RepositoryResolver.findResourceUsingPattern(RepositoryResolver.java:97)
	at org.apache.ivy.plugins.resolver.AbstractPatternsBasedResolver.findResourceUsingPatterns(AbstractPatternsBasedResolver.java:96)
	at org.apache.ivy.plugins.resolver.AbstractPatternsBasedResolver.findIvyFileRef(AbstractPatternsBasedResolver.java:66)
	at org.apache.ivy.plugins.resolver.BasicResolver.getDependency(BasicResolver.java:228)
	at org.apache.ivy.plugins.resolver.ChainResolver.getDependency(ChainResolver.java:104)
	at org.apache.ivy.core.resolve.IvyNode.loadData(IvyNode.java:169)
	at org.apache.ivy.core.resolve.VisitNode.loadData(VisitNode.java:292)
	at org.apache.ivy.core.resolve.ResolveEngine.fetchDependencies(ResolveEngine.java:714)
	at org.apache.ivy.core.resolve.ResolveEngine.doFetchDependencies(ResolveEngine.java:799)
	at org.apache.ivy.core.resolve.ResolveEngine.fetchDependencies(ResolveEngine.java:722)
	at org.apache.ivy.core.resolve.ResolveEngine.getDependencies(ResolveEngine.java:594)
	at org.apache.ivy.core.resolve.ResolveEngine.resolve(ResolveEngine.java:234)
	at xsbt.boot.Update.xsbt$boot$Update$$lockedApply(Update.scala:106)
	at xsbt.boot.Update$$anon$4.call(Update.scala:100)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at xsbt.boot.Update.apply(Update.scala:101)
	at xsbt.boot.Launch.update(Launch.scala:352)
	at xsbt.boot.Launch.xsbt$boot$Launch$$retrieve$1(Launch.scala:208)
	at xsbt.boot.Launch$$anonfun$3.apply(Launch.scala:216)
	at scala.Option.getOrElse(Option.scala:120)
	at xsbt.boot.Launch.xsbt$boot$Launch$$getAppProvider0(Launch.scala:216)
	at xsbt.boot.Launch$$anon$2.call(Launch.scala:196)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at xsbt.boot.Launch.locked(Launch.scala:238)
	at xsbt.boot.Launch.app(Launch.scala:147)
	at xsbt.boot.Launch.app(Launch.scala:145)
	at xsbt.boot.Launch$.run(Launch.scala:102)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.util.NoSuchElementException
	at java.util.StringTokenizer.nextToken(StringTokenizer.java:349)
	at sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:1805)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1299)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	... 55 more

can someone help?

**Comment by allixender** [comment]
Hi zsyet,

it seems the sbt resolver might want to load the sbt-launch.jar from an old repo location. We're checking to get the resolution to the new location.

What you could try though is to replace the `sbt` script in your source folder with the latest version from here: 
https://github.com/paulp/sbt-extras/blob/master/sbt

We're just testing this, too.

Please let us know if that worked for you.

Cheers,
Alex

**Comment by allixender** [comment]
For some reason I believe we won't get more feedback and that the sbt update has solved dependency resolution.

**Comment by lossyrob** [comment]
This should be resolved with the newer SBT script
