### ISSUE TITLE
Exception in JsonFeatureCollection.getAllMultiPolygons if none are present

### ISSUE THREAD

**Issue by RickMohr** [geotrellis/geotrellis#1441]
Here is minimal code to reproduce, extracted from a failure in OTM modeling. I have not run it outside of the app so I am not positive this will fail, but I believe it will. GeoTrellis 0.10.0.RC3

```scala
import geotrellis.vector.io._
import geotrellis.vector.io.json._

def bug() = {
  val geoJson = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"properties\":{},\"geometry\":{\"type\":\"Polygon\",\"coordinates\":[[[-93.38584899902344,45.04344838585674],[-93.3013916015625,45.017243565102596],[-93.39546203613281,44.987627391684704],[-93.38584899902344,45.04344838585674]]]}}]}"
  val featureColl = geoJson.parseGeoJson[JsonFeatureCollection]
  featureColl.getAllMultiPolygons
}
```

```
java.lang.NoSuchMethodError: spray.json.DeserializationException$.$lessinit$greater$default$3()Lscala/collection/immutable/List;
at geotrellis.vector.io.json.GeometryFormats$MultiPolygonFormat$.read(GeometryFormats.scala:156)
at geotrellis.vector.io.json.GeometryFormats$MultiPolygonFormat$.read(GeometryFormats.scala:150)
at spray.json.JsValue.convertTo(JsValue.scala:31)
at geotrellis.vector.io.json.JsonFeatureCollection$$anonfun$getAll$1$$anonfun$1.apply(JsonFeatureCollection.scala:58)
at scala.util.Try$.apply(Try.scala:161)
at geotrellis.vector.io.json.JsonFeatureCollection$$anonfun$getAll$1.apply(JsonFeatureCollection.scala:58)
at geotrellis.vector.io.json.JsonFeatureCollection$$anonfun$getAll$1.apply(JsonFeatureCollection.scala:57)
at scala.collection.immutable.List.foreach(List.scala:318)
at geotrellis.vector.io.json.JsonFeatureCollection.getAll(JsonFeatureCollection.scala:57)
at geotrellis.vector.io.json.JsonFeatureCollection.getAllMultiPolygons(JsonFeatureCollection.scala:83)
```

**Comment by echeipesh** [comment]
Checking this against RC3 does not reproduce the error:
```scala
Welcome to Scala version 2.10.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_80).
Type in expressions to have them evaluated.
Type :help for more information.

scala> import geotrellis.vector.io._
import geotrellis.vector.io._

scala> import geotrellis.vector.io.json._
import geotrellis.vector.io.json._

scala>  val geoJson = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"properties\":{},\"geometry\":{\"type\":\"Polygon\",\"coordinates\":[[[-93.38584899902344,45.04344838585674],[-93.3013916015625,45.017243565102596],[-93.39546203613281,44.987627391684704],[-93.38584899902344,45.04344838585674]]]}}]}"
geoJson: String = {"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[-93.38584899902344,45.04344838585674],[-93.3013916015625,45.017243565102596],[-93.39546203613281,44.987627391684704],[-93.38584899902344,45.04344838585674]]]}}]}

scala>   val featureColl = geoJson.parseGeoJson[JsonFeatureCollection]
featureColl: geotrellis.vector.io.json.JsonFeatureCollection = geotrellis.vector.io.json.JsonFeatureCollection@14a4b8dc

scala>   featureColl.getAllMultiPolygons
res0: Vector[geotrellis.vector.MultiPolygon] = Vector()

scala> 
```

That method it's failing to find (`spray.json.DeserializationException$.$lessinit$greater$default$3()`) is some default value for `DeserializationException` object. So it's looking like some kind of binary incompatibility. Could you double check what else might be bringing in `spray-json` of a different version?

**Comment by echeipesh** [comment]
This is a good tool to quickly check your dependencies, if you haven't come across it yet: https://github.com/jrudolph/sbt-dependency-graph

**Comment by RickMohr** [comment]
Thanks. Fixed by upgrading spray to 1.3.3 and sprayJson to 1.3.2 (the latest versions).

**Comment by RickMohr** [comment]
Spoke too soon. Still investigating.

**Comment by RickMohr** [comment]
For the record, running the lines (as above) in the `sbt` `console` of `otm-modeling` succeeds.

**Comment by echeipesh** [comment]
Perhaps when it's being loaded by SJS there is already a loaded version of spay.json that conflicts? This would prevent JVM from loading the intended version.

**Comment by RickMohr** [comment]
This was resolved, either by using newer versions of the spark and spark-jobserver containers, or by clearing and rebuilding `.ivy2/cache`.

Thanks for the help.
