### ISSUE TITLE
coordinate transformation error - java.lang.ArrayIndexOutOfBoundsException: 1840

### ISSUE THREAD

**Issue by ericq** [geotrellis/geotrellis#899]
When I inject a NAD83_UTM_zone_11N to the HDFS, the reprojection is invoked but got the following issue.

14/10/01 12:55:31 ERROR executor.Executor: Exception in task ID 0
java.lang.ArrayIndexOutOfBoundsException: 1840
        at geotrellis.raster.reproject.RowTransform$.geotrellis$raster$reproject$RowTransform$$computeApprox(RowTransform.scala:76)
        at geotrellis.raster.reproject.RowTransform$.geotrellis$raster$reproject$RowTransform$$computeApprox(RowTransform.scala:68)
        at geotrellis.raster.reproject.RowTransform$.geotrellis$raster$reproject$RowTransform$$computeApprox(RowTransform.scala:68)
        at geotrellis.raster.reproject.RowTransform$.geotrellis$raster$reproject$RowTransform$$computeApprox(RowTransform.scala:68)
        at geotrellis.raster.reproject.RowTransform$$anonfun$approximate$1.apply(RowTransform.scala:34)
        at geotrellis.raster.reproject.RowTransform$$anonfun$approximate$1.apply(RowTransform.scala:24)
        at geotrellis.raster.reproject.Reproject$.apply(Reproject.scala:70)
        at geotrellis.raster.reproject.package$ReprojectExtentsion.reproject(package.scala:22)
        at geotrellis.raster.reproject.package$ReprojectExtentsion.reproject(package.scala:16)
        at geotrellis.spark.ingest.Ingest$$anonfun$geotrellis$spark$ingest$Ingest$$_reproject$1$1.apply(Ingest.scala:63)
        at geotrellis.spark.ingest.Ingest$$anonfun$geotrellis$spark$ingest$Ingest$$_reproject$1$1.apply(Ingest.scala:60)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.TraversableOnce$class.reduceLeft(TraversableOnce.scala:172)
        at scala.collection.AbstractIterator.reduceLeft(Iterator.scala:1157)
        at org.apache.spark.rdd.RDD$$anonfun$17.apply(RDD.scala:790)
        at org.apache.spark.rdd.RDD$$anonfun$17.apply(RDD.scala:788)
        at org.apache.spark.SparkContext$$anonfun$23.apply(SparkContext.scala:1116)
        at org.apache.spark.SparkContext$$anonfun$23.apply(SparkContext.scala:1116)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:111)
        at org.apache.spark.scheduler.Task.run(Task.scala:51)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
14/10/01 12:55:31 WARN scheduler.TaskSetManager: Lost TID 0 (task 0.0:0)
14/10/01 12:55:31 WARN scheduler.TaskSetManager: Loss was due to java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException: 1840
        at geotrellis.raster.reproject.RowTransform$.geotrellis$raster$reproject$RowTransform$$computeApprox(RowTransform.scala:76)
        at geotrellis.raster.reproject.RowTransform$.geotrellis$raster$reproject$RowTransform$$computeApprox(RowTransform.scala:68)
        at geotrellis.raster.reproject.RowTransform$.geotrellis$raster$reproject$RowTransform$$computeApprox(RowTransform.scala:68)
        at geotrellis.raster.reproject.RowTransform$.geotrellis$raster$reproject$RowTransform$$computeApprox(RowTransform.scala:68)
        at geotrellis.raster.reproject.RowTransform$$anonfun$approximate$1.apply(RowTransform.scala:34)
        at geotrellis.raster.reproject.RowTransform$$anonfun$approximate$1.apply(RowTransform.scala:24)
        at geotrellis.raster.reproject.Reproject$.apply(Reproject.scala:70)
        at geotrellis.raster.reproject.package$ReprojectExtentsion.reproject(package.scala:22)
        at geotrellis.raster.reproject.package$ReprojectExtentsion.reproject(package.scala:16)
        at geotrellis.spark.ingest.Ingest$$anonfun$geotrellis$spark$ingest$Ingest$$_reproject$1$1.apply(Ingest.scala:63)
        at geotrellis.spark.ingest.Ingest$$anonfun$geotrellis$spark$ingest$Ingest$$_reproject$1$1.apply(Ingest.scala:60)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.TraversableOnce$class.reduceLeft(TraversableOnce.scala:172)
        at scala.collection.AbstractIterator.reduceLeft(Iterator.scala:1157)
        at org.apache.spark.rdd.RDD$$anonfun$17.apply(RDD.scala:790)
        at org.apache.spark.rdd.RDD$$anonfun$17.apply(RDD.scala:788)
        at org.apache.spark.SparkContext$$anonfun$23.apply(SparkContext.scala:1116)
        at org.apache.spark.SparkContext$$anonfun$23.apply(SparkContext.scala:1116)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:111)
        at org.apache.spark.scheduler.Task.run(Task.scala:51)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by lossyrob** [comment]
@ericq: Was this issue resolved? I know we worked through some issues on the mailing list, if this is resolved I'd like to close it out.
