### ISSUE TITLE
Spark - import and export test - java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ericq** [geotrellis/geotrellis#905]
Hi, 

I use the Hadoop import (HadoopIngestCommand) to ingest the nnd.tif (under the spark test) and then I use the geotrellis.spark.cmd.Export. 
The export process shows the ArrayIndexOutOfBoundsException (attached in the end)

Is this something to do with the metadata generated as the result of the ingest process:

{"cellType":"int8","extent":{"xmin":-122.10125959693755,"ymin":32.254645234928425,"xmax":-113.34259191436875,"ymax":39.20172398957597},"crs":"+proj=latlong +datum=WGS84 +to_meter=1.0 ","layoutLevel":{"id":12,"tileLayout":{"tileCols":4096,"tileRows":2048,"pixelCols":512,"pixelRows":512}},"tileIndexScheme":"row_index"}

But in Arcgis, I have the following info of the same nnd.gif file. 
cols, rows: 5120, 4608

So, could you please explain

(1) during the ingestion: why the metadata.json has a different cols and rols. and why the orginal cols and rows are not preserved. 
(2) what's wrong with the export process?  

-- Exception of the export process --
14/10/07 12:15:24 ERROR executor.Executor: Exception in task ID 0
java.lang.ArrayIndexOutOfBoundsException: 393216
        at geotrellis.raster.FloatArrayTile.applyDouble(FloatArrayTile.scala:33)
        at geotrellis.raster.DoubleBasedArray$class.apply(DoubleBasedArrayTile.scala:25)
        at geotrellis.raster.FloatArrayTile.apply(FloatArrayTile.scala:28)
        at geotrellis.raster.ArrayTile$class.toArray(ArrayTile.scala:197)
        at geotrellis.raster.FloatArrayTile.toArray(FloatArrayTile.scala:28)
        at geotrellis.raster.io.geotiff.Encoder.<init>(Encoder.scala:65)
        at geotrellis.raster.io.geotiff.Encoder$.writePath(Encoder.scala:392)
        at geotrellis.raster.io.geotiff.GeoTiffWriter$.write(GeoTiffWriter.scala:30)
        at geotrellis.spark.cmd.Export$$anonfun$exportTiles$2.apply(Export.scala:135)
        at geotrellis.spark.cmd.Export$$anonfun$exportTiles$2.apply(Export.scala:130)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at org.apache.spark.rdd.RDD$$anonfun$foreach$1.apply(RDD.scala:703)
        at org.apache.spark.rdd.RDD$$anonfun$foreach$1.apply(RDD.scala:703)
        at org.apache.spark.SparkContext$$anonfun$runJob$4.apply(SparkContext.scala:1080)
        at org.apache.spark.SparkContext$$anonfun$runJob$4.apply(SparkContext.scala:1080)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:111)
        at org.apache.spark.scheduler.Task.run(Task.scala:51)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by lossyrob** [comment]
@ericq: Was this issue resolved? I know we worked through some issues on the mailing list, if this is resolved I'd like to close it out.
